### ISSUE TITLE
Create useful alert classes in uniform

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Uniform.css#1]
Right now there are some classes for alerts in uniform but those are basically useless. Most of the time You would like to use alert classes similar like You would do in the light DOM. The solution for that would be, instead of implementing classes directly in uniform like It's done now, add those classes in `::slotted( )`. Then It would be able to use them on slotted elements.

**Comment by alshakero** [comment]
Good idea!

**Comment by alshakero** [comment]
Fixed in https://github.com/Starcounter/Uniform.css/commit/a1cab85479880383d7df198d872f2046b3386988
