### ISSUE TITLE
Implement uni-data-table

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#112]
Implement `uni-data-table`, a custom element that is an adapter to `vaadin-grid`.

It will use helper elements:
- `uni-data-table-provider` to provide the data source, column configuration and the index of the selected row. Column configuration should assume a certain view-model structure that includes column width, header, sorting triggers, filter query input.
- `uni-data-table-column` to provide a HTML template for each column, which might use data binding. Other parts of column configuration (width, header) do not come from this element but from column configuration in `uni-data-table-provider` (single source of truth).

Multiselect is not needed now.

The helper elements can be provided in light DOM or slotted.

@tomalec can you pls provide the proposed API that we discussed on Wednesday with @malx122, @platosha and @PatrykSzwer?

**Comment by tomalec** [comment]
So the api is expressed in following code:

Content part:
```html
<h3 ...>Header</h3>
<button ...>
<input ...>
<!-- 
  After a `setTimeout(0)` if not stopped via API agreed with `<uni-data-table>`.
  will display a message (in element's shadow DOM) with some information 
  about the content of data and suggested way to presnet it. 
  The message will be hidden by `uni-data-table` 
-->
<uni-data-table-provider slot="AppA/person-data"
    data="{{json in specified format}}"
    columns="{{json in specified format}}"
    filters="{{}}"
    selected="{{array of selected indexes, or index}}"
    multiselect></uni-data-table-provider>

<template is="declarative-shadow-dom">
    <uni-data-table>
        #shadow-root <-element's shadow root
            <vaadin-grid data="{data from distributed element}">
                <!-- column templates forwarded to vaadin -->
                <!-- data element could also be distributed, as long as it's not displayed but does not have to, as long as `<uni-data-table>` already fetched the data-->
                <slot></slot>
            </vaadin-grid>
        #/shadow-root
        <!-- customized version by solution owner -->
        <uni-data-table-column><template></template></uni-data-table-column>
        <uni-data-table-column><template></template></uni-data-table-column>
        <slot name="AppA/person-data"></slot>
    </uni-data-table>
</template>
```



------

For developers that would like to purposefully block the composability of such data, could use the `uni-data-table` in their content part.

```html
<uni-data-table>
    <uni-data-table-provider
        data="{}"
        columns="{}"
        filters="{}"
        selected="{}"
        multiselect></uni-data-table-provider>
    <!-- customized column setup -->
    <uni-grid-column><template></template></uni-grid-column>
    <uni-grid-column><template></template></uni-grid-column>
</uni-data-table>
```

**Comment by tomalec** [comment]
Also we agreed, that default theme of `uni-data-table` would have a hover effect for rows.
This could be eventually styled or themed using `::part("row"):hover`

**Comment by platosha** [comment]
Made a very sketchy prototype there: https://github.com/Starcounter/uniform.css/tree/feature/uni-data-table

The API structure seems to work fine so far.

Something missing in the API proposal is how to handle infinite scrolling. We had a brief discussion about this with @tomalec, this is the idea we came up with:
- Make a property for the displayed data slice(s) on the provider element.
- As `<vaadin-grid>` requests a new data slice, the provider updates the property. If bound to a view-model, the server gets notified of this change and send a JSON patch with the data slice contents.
- The provider observes for the data property using Polymer’s array splices observer. JSON patches with the data slices notify the provider.
- After provider data change notification, `<uni-data-table>` invokes the `<vaadin-grid>`’s data callback. This is required to render the data that comes asynchronously.

**Comment by tomalec** [comment]
@PatrykSzwer do you have any data structure samples? (https://github.com/Starcounter/KitchenSink/issues/229)

**Comment by PatrykSzwer** [comment]
Yes, first prototype of proposed structure looks like this:
```
{
  "Grid": {
    "Columns": [
      {
        "Header": "",
        "Path": "",
        "Frozen": false, // For the Freezing feature of vaadin grid
        "Hidden": false,
        "Resizable": false,
        "SortDirection": "", // asc, desc or empty string for no sorting
        "Filter": "" // Filter string, part of the last name e.g
      }
    ],
    "Data": [
      {
        "RowString": [{ }] // Array of objects
      }
    ]
  } 
}
```

After discussion with @tomalec and @platosha we weren't entirely sure if `Path` value in the column part of the model is necessary or not. Please write your thoughts about that if you came up with some conclusion.

**Comment by tomalec** [comment]
As we noticed with @platosha we missed yesterday important part. What is about to be inside 
```html
<!-- customized version by solution owner -->
<uni-data-table-column><template></template></uni-data-table-column>
<uni-data-table-column><template></template></uni-data-table-column>
```
Unless we want to limit ourselves (and app devs) to use text content only.

To make it render anything it needs to contain data binding:
```html
<uni-data-table-column>
  <template class="header">Name</template>
  <template>
    {{item.First}} {{item.Last}} 
    <a href=""><img src="{{item.GHAvatar}}">{{item.UserName}}</a>
  </template>
</uni-data-table-column>
```

What means an exceptional case of using data binding in shadow dom. But what concenrs me the most put's lots of responsibility and load on solution owner.

Given our blendend view-models are usually huge, even individual app view-models are not described publicly, solution owner would have to figure out what property is delivers what kind of content etc, also He would have to be carefull not to get too deep in model tree to access data from other apps which may break lot's of things when they are stopped or chaged.

All the alternative solutions we were able to thik off, could be reduced to use regualr `<vaadin-grid>` in light dom with `<starcounter-include>` in a cell, then shadow dom composition in cell's view.

We would really appreciate real customer/user feedback to limit the requirements.
@malx122, @LarsTjernstrom, @warpech

**Comment by warpech** [comment]
It is enough that I can put starcounter-include in a cell. For the data table, we don't need custom compositions of cell contents.

But we need to use Uniform classes in table cells somehow.

**Comment by tomalec** [comment]
> It is enough that I can put starcounter-include in a cell.  

Please note that [the API we agreed on the meeting](https://github.com/Starcounter/uniform.css/issues/112#issuecomment-395356522) does not allow that.

neither setting uniform classes.

**Comment by tomalec** [comment]
> It is enough that I can put starcounter-include in a cell.  

Please note that [the API we agreed on the meeting](https://github.com/Starcounter/uniform.css/issues/112#issuecomment-395356522) does not allow that.

**Comment by PatrykSzwer** [comment]
At today's meeting we agreed to a new view-model structure. This is our current proposal:
```
{
  "Grid": {
    "Columns": [
      {
        "SortDirection": "", // asc, desc or empty string for no sorting
        "Filter": "" // Filter string, part of the last name e.g
      }
    ],
    "Data": [
      { // Example structure of row data
        "FirstName": "",
        "LastName": "",
        "TriggerX": 0
      }
    ],
    "Page": 0, // For infinite scroll
    "AddNewRow": 0 // Trigger to add new row
  }
}
```

**Comment by PatrykSzwer** [comment]
Example implementation can be tracked here: https://github.com/Starcounter/KitchenSink/tree/uni-data-table

**Comment by tomalec** [comment]
On todays meeting we also agreed that 
1. we should support `DocumentFragment`s in cell templates with Polymer data binging and any HTML structure.
2. we should have 1 way to do that.
3. we will keep data binding and cell templates in the content (light DOM) part,
4. we would like to have a way to compose and enhance grid internals in presentation layer as drafted at https://github.com/Starcounter/uniform.css/issues/112#issuecomment-395795723 (probably with slight syntax changes, like `<template>` per column, not row).
5. we will not focus on it right now, as there is no customer demand for it yet, we will start simple to provide solid support for requested, simpler use cases.
6. If app dev would like to expose fully features blendability of `uni-data-table` row, he/she could use `starcounter-include` as a grid cell template.
6. Column configuration should be provided declaratively in markup as it is done in `vaadin-grid`.
10. `uni-data-table` should support row details, like `vaadin-grid` does.
8. We agreed that more-or-less `vaadin-grid` is enough, we would like to make an alias (wrapper) with slightly adjusted API, so we will have a place for further improvements without a need to change of apps source code.
7. grid row data (`.Rows[*]`), could contain **any** merged or not view model, it's structure is not limited by `uni-data-table`, neither on client- nor server-side.
7. `uni-data-table` should be usable in light DOM as well as in shadow - application developer should import it explicitly where he/she uses it.
8. We will allow the use of Uniform (`.css` and components) in the light DOM. This allows app developers to use `uni-button`s, etc. in the `uni-data-table` cells without a hassle, overhead with declarative shadow DOM, nor `starcounter-include`.


Example, convereted https://github.com/Starcounter/Blending/blob/7ff2c4d82e738a2d71ca199b21947caa2b762707/src/BlendingEditor/wwwroot/BlendingEditor/views/LayoutConditionsPage.html

```html
<link rel="import" href="/sys/polymer/polymer.html">
<link rel="preload" as="style" href="/sys/uniform/components/uni-date-table.html">

<template>
    <dom-bind>
        <template is="dom-bind">
            <h2 slot="blendingeditor/layout-conditions-header">{{model.LayoutConditionsHeader}}</h2>
            <uni-date-table
                slot="blendingeditor/layout-conditions-table"
                data="{{model.LayoutConditions - an object returned by server-side helper that contains what was prviously model.LayoutConditions as data.Rows}}"
                selected="{{array of selected rows -indexes, or index}}"
                multiselect>
                <uni-data-table-col style="width: 5%">
                    <template uni-header>Order</template>
                    <template>
                        <svg width="20px" height="30px" aria-hidden="true" viewBox="0 0 1000 1000" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <use xlink:href="/BlendingEditor/images/drag.svg#icon"></use>
                        </svg>
                    </template>
                </uni-data-table-col>
                <uni-data-table-col style="width: 10%">
                    <template uni-header>Layout</template>
                    <template><div>{{item.ParentLayoutName}}</div></template>
                </uni-data-table-col>
                <uni-data-table-col style="width: 60%">
                    <template uni-header>
                        <!-- Column template could use any HTML structure -->
                        <span
                            style="cursor: help"
                            title="Layout conditions support Starcounter URI wildcard formatting.
                                    For example, you can use the following Layout condition URIs: `/app/resource/{?}`, `/app/resource/{?}/edit`, `/app/query?{?}`.">
                           URIℹ️
                       </span>
                    </template>
                    <template>
                        <!--
                            `uni-data-table` assings individual model as `item`,
                            so it could be further used with Polymer data binding as usual
                        -->
                        <input type="text" value="{{item.Url$::change}}">
                    </template>
                </uni-data-table-col>
                <uni-data-table-col style="width: 10%">
                    <template uni-header>Headers</template>
                    <template>
                        <label>
                            <!-- this is how vaadin-grid opens details panel, we can use button as well -->
                            <input type="checkbox" checked="{{detailsOpened}}">
                            Headers ({{item.Headers.length}})
                        </label>
                    </template>
                </uni-data-table-col>
                <!-- Row detail follows Vaadin convention -->
                <template uni-row-details>
                    <table class="blendingeditor-table" style="width: initial">
                        <thead>
                            <tr>
                                <th>Header key</th>
                                <th>Header value</th>
                                <th>Partial matching</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <!--
                                `uni-data-table` assings individual model as `item`,
                                so it could be further used with Polymer data binding as usual
                            -->
                            <template is="dom-repeat" items="{{item.Headers}}" as="itemHeader">
                                <tr>
                                    <td>
                                        <input type="text" value="{{itemHeader.Name$::change}}">
                                    </td>
                                    <td>
                                        <input type="text" value="{{itemHeader.Value$::change}}">
                                    </td>
                                    <td>
                                        <input type="checkbox" checked="{{itemHeader.PartialMatching$::change}}">
                                    </td>
                                    <td>
                                        <button type="button" value="{{itemHeader.DeleteTrigger$::click}}" onmousedown="++this.value;" title="Remove layout condition header">
                                            Delete
                                        </button>
                                    </td>
                                </tr>
                            </template>
                        </tbody>
                    </table>
                    <button type="button" value="{{item.AddHeaderTrigger$::click}}" onmousedown="++this.value;" title="Add new layout condition header">
                        Add header
                    </button>
                </template>
            </uni-data-table>
            …
        </template>
    </dom-bind>
    <template is="declarative-shadow-dom">
        <link rel="stylesheet" href="/sys/uniform.css/uniform.css">
        <link rel="stylesheet" href="/BlendingEditor/css/blendinguniform.css">
        <div class="uni-section-secondary uni-title">
            <slot name="blendingeditor/layout-conditions-header"></slot>
        </div>
        <div class="uni-section-primary blendingeditor-section-primary-grid">
            <div class="uni-card">
                <slot name="blendingeditor/layout-conditions-table"></slot>
                …
            </div>
        </div>
    </template>
</template>
```

**Comment by platosha** [comment]
Here are some findings for the view-model I’ve learned so far.

### It should explicitly contain the total number of all rows

The total number of rows is often bigger than the initial number of rows in the view-model, which initially contains the first “page” only.

Knowing the total number of rows in `<uni-data-table>` is more pretty for the end user. This allows to predict the total scroll height and avoid scrollbar jumps.

In my PR, I use the `Size` property in the view-model for the total number of rows.

### It should contain the page size

`<uni-data-table>` expects a “page” to contain a certain number of rows. The same number is used in the server’s response handler, so they should be kept in sync. I would suggest that this number is added to view-model on the server side, instead of using duplicated values on the server and on the client.

In my PR, I’ve added the `PageSize` property for this.

### Using a single sparse array for rows might not be optimal

On end-user scrolling, `<uni-data-table>` requests new pages from the server. Usually, this goes one by one in order, e. g., page `2` is requested after page `1`, and so on. However when scrolling goes very fast, it sometimes skip requesting some pages that was quickly scrolled away.

With the PRs I have, quick scrolling results in empty rows in the grid, because the server response is incorrect. For example,
- let’s assume the `PageSize` is 10,
- the end user was reading the initial page `0`, then quickly scrolls the page `1` away and stops scrolling at page `2`
- the server is expected to splice the `Rows` and add the rows of the page `2` (indexes from 20 to 29), while page `1` is still missing (indexes 10...19 remain undefined)
- now this is hard for me to code in C#. I have this in C#: `this.Rows = Rows.Take(offset).Concat(PageRows).Concat(Rows.Skip(offset + PageSize));`, but this seems incorrect for this case (`offset` is bigger than `Rows.Count()`), the resulting JSON patch uses indexes from 10...19 instead of skipping them and using 20...29, which correspond to the page 2.

On the client this gets tricky too. After the JSON patch is applied, `<uni-data-table>` has to recognise which page was updated to call the request callback. I the PR, I have to calculate the page number from the spliced `Rows` array indexes.

I think, we could simplify this if we would change the view-model of `Rows` to be something like:
```js
{
  "Page$": 0,
  "PageSize": 25,
  "RowsByPage": { // Object with numeric keys (or an Array)
    // Keys are the `Page` numbers, values are arrays of rows on the page
    "0": [
      {
        // Example row data structure
        "FirstName": "" //, ...
      }
    ]
  }
}
```

So that when a page of rows is requested, it is delivered using an object key update, instead of an array splice. Hopefully that would be easier both on the server and on the client.

**Comment by tomalec** [comment]
Even though JSON Patch should play well with sparse tables, as you can add an array item to the index beyond its current size. But if `vaadin-grid` is bound to the concept of the page so heavily, `uni-data-grid` and C# helper are the places to hide it as an implementation detail.

If client-side code requires a concept of a rows Page I'd say server-side should follow to express what's on the screen consistently. This will allow making our translation layer simpler and easier to maintain.

**Comment by PatrykSzwer** [comment]
I've talk with Anton and we agreed to try use array of the objects with array inside (so basically array of arrays) to reflect indexing (It's already on branch). If this will not work then we will just simply add information about rowPage to rowsPerPage collection (Anton wanted to avoid this solution at first, due to some complications on the client side implementation

**Comment by warpech** [comment]
For each Uniform component, I would like to have the view-model explained in README.md. Right now the example in https://github.com/Starcounter/uniform.css/issues/112#issuecomment-396234281 seems outdated (it only holds a single page of rows) and https://github.com/Starcounter/uniform.css/issues/112#issuecomment-397594997 seems incomplete (it does not have column definition).

Can you pls maintain the suggested view-model explanation in https://github.com/Starcounter/uniform.css/blob/feature/uni-data-table/components/uni-data-table/README.md?

**Comment by joozek78** [comment]
From C# perspective I'd like us to support following:

I specify in my C# code where the data comes from and which columns should be displayed. Each property is assumed to be textual, if it's not I can override how it's rendered. The object configuring the table and holding the state of filters, sorting and pagination has following structure:
```js
{
    Columnns: [{
        DisplayName: "", // used when generating default headers
        PropertyName: "", // used to match properties in each row to corresponding column. Rows data need to have those properties.
        SortingEnabled: true,
        FilteringEnabled: true,
        Sort$:"", // used to communicate how the user wants this column to be sorted: asc,desc,none
        Filter$:"", // used to communicate how the user wants this column to be filtered
        // following could be added later to support richer filtering:
        FilteringOperator$: "",
        Type: "", // to present supported filtering methods
    }],
    CurrentPage$: 0,
    PageSize$: 20,
}
```

The object holding rows has following structure:
```js
{
    Pages:[{
        Rows: [{}] // array of specific row objects
    }],
    TotalRows: 0 // total number of rows, even those not loaded yet
}
```

The configuration object is built by app developer with help of C# code that we (Starcounter) provide. I imagine the app developer will then be able to write as little code as possible to create the data table in html, like in this example:

```html
<uni-data-table slot="kitchensink/datatable-data-table"
                rows-data="{{model.RowData}}"
                configuration="{{model.TableConfiguration}}">
    <uni-data-table-column index="0">
        <template slot="header">
            <!-- only overriding how header for 1st column is displayed -->
            <header-em>First</header-em> name
        </template>
    </uni-data-table-column>
    <uni-data-table-column index="1">
        <template>
            <!-- only overriding how cells in second column are displayed -->
            <date-picker value="{{item.DateOfBirth$}}"/>
            <!-- the headers and cells in all other columns are generated -->
        </template>
    </uni-data-table-column>
</uni-data-table>
```

Note, that I didn't divide this code into light and shadow dom. That's because I don't really know how that should be done, and I don't want to interfere in this. I just want to create a grid with as little boilerplate as possible.

Questions
---
1. Do you agree with my `Configuration` and `RowData` structures?
1. Can we have `uni-data-table` that works without explicit column and row declarations in html?

**Comment by joozek78** [comment]
BTW is infinite scroll required by some technical reasons? It would be preferable to also support traditional paging, with jumping to specific page.

**Comment by PatrykSzwer** [comment]
Infinite scroll is by default used in `vaadin-grid` and our plan was to support this at the beginning and then expand that to support pagination also.

**Comment by joozek78** [comment]
@platosha @tomalec I've updated my comment. Please take a look and tell me what you think

**Comment by platosha** [comment]
@joozek78 overall, the structure of `{{model.Table}}` is getting quite deep, and this might be annoying in case if someone would actually like bind to nested properties.

Consider: as a developer, I want to customize first column header content, and reuse the column title defined in the backend.

```html
<uni-data-table provider="{{model.Table}}">
    <uni-data-table-column index="0">
        <template slot="header">
            <my-custom-markup>{{model.Configuration.Columns.0.DisplayName}}</my-custom-markup>
        </template>
    </uni-data-table-column>
</uni-data-table>
```

Consider: as a developer, I want to present the selected row’s data in a separate view

```html
<uni-data-table provider="{{model.Table}}"></uni-data-table>
<my-user-view user="{{model.Table.Configuration.SelectedRows.0}}"></my-user-view>
```

It feels like would be better to remove the `Configuration` grouping from the structure, and have `Table.Columns` and `Table.SelectedRows` instead.

Same with the `.Pages` and `.TotalRows` keys. I don’t really see a reason for grouping them under `Data.Pages` and `Data.TotalRows`. If there aren’t any reasons, maybe it’s better to have them right in the `Table` level.

I guess, `PaginationConfiguration` grouping has reasoning, however, because that would allow to reuse the pagination view-model structure in other places, e. g., with generic `<uni-pagination>` model provider, not necessarily related with `<uni-data-table>`.

**Comment by tomalec** [comment]
I also vote for flattening `Configuration` and `PaginationConfiguration` for the reasons mentioned above.

**Comment by PatrykSzwer** [comment]
BTW just a small note about your VM @joozek78. Keyword `Data` is restricted and not allowed in Typed JSON.

**Comment by joozek78** [comment]
@platosha @tomalec I've updated the view-model according to your suggestions. I've also added triggers for pagination. We begin server-side implementation with @PatrykSzwer using this structure

**Comment by PatrykSzwer** [comment]
One note: correct me if I'm wrong, but isn't that triggers `NextPageTrigger$` and `PreviousPageTrigger$` are redundant, and can be replaced just by handler on `CurrentPageIndex$`, and client-side on e.g clicking next page would just do `CurrentPageIndex + 1`?

**Comment by platosha** [comment]
@PatrykSzwer I think you’re right, they are redundant. Can confirm, I have already tried using a built-in `<uni-pagination>` with `<uni-data-table>` with the same backend as with “infinite” scrolling with a single trigger for `Page$` index.

`PagesCount` is redundant too, as this can be easily calculated on the client side from the `PageSize` and `TotalRows`.

BTW @joozek78 Why is the `PageSize` writable? Is it intended for “Show X items on a page” kind of selectors?

**Comment by joozek78** [comment]
> PagesCount is redundant too, as this can be easily calculated on the client side from the PageSize and TotalRows.

Well yes, we can calculate that on either end. I just imagined we'd do that in the backend, since frontend should have no business logic. I'm not sure if calculating total pages is business or presentation logic, and I don't really think it's important. Let's just have one place for it

> BTW @joozek78 Why is the PageSize writable? Is it intended for “Show X items on a page” kind of selectors?

Yes, I imagine the user could change that. That might be implemented in the future though, to prioritize more important stuff

**Comment by platosha** [comment]
> I'm not sure if calculating total pages is business or presentation logic

The choice between “infinite scrolling” and paginated modes of `<uni-data-table>` is presentation logic, I assume. The frontend needs `TotalRows` for the “infinite scrolling” mode.

For the sake of more similarity and unification of how both “infinite” and paginated modes work, I would suggest for both of them to use the same `TotalRows` and `PageSize` from the view-model, instead of using different keys of the view-model in different modes.

**Comment by joozek78** [comment]
> For the sake of more similarity and unification of how both “infinite” and paginated modes work, I would suggest for both of them to use the same TotalRows and PageSize from the view-model, instead of using different keys of the view-model in different modes.

Of course

**Comment by warpech** [comment]
@PatrykSzwer:

> One note: correct me if I'm wrong, but isn't that triggers `NextPageTrigger$` and `PreviousPageTrigger$` are redundant, and can be replaced just by handler on `CurrentPageIndex$`, and client-side on e.g clicking next page would just do `CurrentPageIndex + 1`?

100% agree with this and this is not negotiable, because the client side component `<uni-pagination><input type="range">` already exists (https://github.com/Starcounter/uniform.css/tree/master/components/uni-pagination) and uses 3 attributes to bind to the data model.

**Comment by joozek78** [comment]
@platosha @tomalec @warpech
I assumed that the `Pages` array existed to cache on frontend rows that were loaded at least once.
Imagine the following scenario:
1. user sets page to 1. first page is loaded from DB into view-model and then into frontend
1. user sets page to 2. second page is loaded from DB into view-model and then into frontend
1. user sets page to 1. again. **Should data be loaded from DB again?** Or should it be loaded from some frontend cache? WDYT?

**Comment by tomalec** [comment]
> If the data should always be loaded from DB then why do we need to expose Pages from the VM? Why can't just the current page be exposed and Pages generated in the frontend?

Frontend needs to keep many pages at once, for example when user is scrolled to 1.5 page, we need to show parts from both, also, this allow us to preload previous and next page in advance if needed.

> user sets the page to `1` again. **Should data be loaded from DB again?** Or should it be loaded from some frontend cache? WDYT?

I'd say usually it should be rendered out of that that already exists in the view model. If there was a reason to invalidate it, client-side would notify the server about it for example by providing filtering details, if there was a change in a row from the previous page, the server can always push a patch for it as well.
Conceptually, I don't consider it a cache, but just a view-model data as any other, as we try to build thin clients, so client just renders what's given.

However, this could be client-side who decides, that user scrolled already 1000's rows, so it could remove old rows from the view-model to save the browser memory, but I imagine such operation to be yet another patch send to the server.

**Comment by warpech** [comment]
> However, this could be client-side who decides, that user scrolled already 1000's rows, so it could remove old rows from the view-model to save the browser memory, but I imagine such operation to be yet another patch send to the server.

The client has no power to remove anything from the view-model.

My proposal: The server has the responsibility to make sure that all loaded pages are up-to-date. For the performance reasons, the server might remove pages from the view-model if they are not neighbors of the current page.

**Comment by joozek78** [comment]
What do you think should happen when the user changes filter/order? Should the current page be reset to 0 (I think so)? This behavior would be implemented on the server side.

**Comment by warpech** [comment]
> What do you think should happen when the user changes filter/order? Should the current page be reset to 0 (I think so)? This behavior would be implemented on the server side.

Yes, I definitely agree.

-----

Closing this issue as `<uni-data-table>` was implemented in https://github.com/Starcounter/uniform.css/releases/tag/0.4.0.

The remaining work is tracked in https://github.com/Starcounter/uniform.css/issues/140, https://github.com/Starcounter/uniform.css/issues/158, https://github.com/Starcounter/Starcounter.Uniform/issues/3
