### ISSUE TITLE
`<uni-form-item>` should reuse the look and feel defined by `.uni-label-control` 

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#125]
During the review of the initial version of `<uni-form-item>` 
@warpech pointed an issue which was not addressed in merged branch [see original discussion here](https://github.com/Starcounter/uniform.css/pull/109#pullrequestreview-131202840)

3. `<uni-form-item>` should reuse the look and feel defined by `.uni-label-control` https://github.com/Starcounter/uniform.css/blob/fc8deead8ac6a13359c4d9ac31cd408639210041/uniform.css#L81-L104 (please extend it to have some style for `> output`)

-----

[_@platosha comment_](https://github.com/Starcounter/uniform.css/pull/109#issuecomment-399921169)

@warpech
> `<uni-form-item>` should reuse the look and feel defined by `.uni-label-control`

Copied and adjusted to look more like in the Rolf’s sketch linked above. The label has a normal font size, but the output is smaller.

-----

[_@warpech comment_](https://github.com/Starcounter/uniform.css/pull/109#issuecomment-400090452)

> Copied and adjusted to look more like in the Rolf’s sketch linked above. The label has a normal font size, but the output is smaller.

Rolf's sketch is a low-fi wireframe that is serves illustration purpose only. The built in class `.uni-label-control` is still the class that should be used for the actual design.

Changes to the look and feel are possible but they should be done by modifying the definition of `.uni-label-control`. In fact, we have open issues for some changes: https://github.com/Starcounter/uniform.css/issues/54

**Comment by warpech** [comment]
This is blocked by https://github.com/Starcounter/uniform.css/issues/121

**Comment by warpech** [comment]
@tomalec this is unblocked now.
