### ISSUE TITLE
How to document features inherited from vaadin-elements?

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#126]
As a followup to @warpech's question at https://github.com/Starcounter/uniform.css/pull/123#issuecomment-399974386

We have a set of features that come from `vaadin-elements`, my questions are:
1. Do we want to mention all of them, or just those we plan to maintain and support in `uni-`?
2. Should we document them by ourselves or just refer the Vaadin docs?

**Comment by tomalec** [comment]
I vote for 
- mentioning ones we plan to support in long term - then we need a list of those.
- maintaining the docs and examples of the basic variants of those, with a link to Vaadin for more,
- mentioning the list of features inherited from Vaadin, which may be used, with a bold note that "current implementation" supports them and please raise a GitHub issue if you want support for it.

**Comment by warpech** [comment]
As the rule of thumb, in Uniform docs, we should not even have to mention that these features are provided by Vaadin. All the APIs that we decide to expose to Starcounter app authors should use the term Uniform or the `uni-` prefix.

So in my opinion, all features inherited from Vaadin should be explicitly copied to our docs. This in fact will be useful for another purpose - our release cycle is solwer than Vaadin, so our docs should always refer to the version of components that is actually provided by StarcounterClientFiles.

**Comment by warpech** [comment]
Archiving as answered. It does not look for me like something is missing now in UniformDocs in this regard. @tomalec if you have something particular in mind, please open an issue in UniformDocs.
