### ISSUE TITLE
Implement `uni-section` and `uni-card`

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#15]
As presented on the design https://drive.google.com/open?id=1HqRZlnwKYFjtQmgkLPtb8hBf3qnB69yO, we need an implementation of full-width visual sections of a view.

I just discussed that with @andwah. We think it can be implemented using a new class `.uni-section` with a negative margin.

Preview:

![all routes](https://user-images.githubusercontent.com/566463/35921587-558d7b68-0c1b-11e8-8ff2-c1baac8f218e.png)

The area to the right of the sidebar is a single `starcounter-include` with a grayish background. By default, `uniform.css` should style the `:host` element (this case it is `starcounter-include`) to have `padding: 20px`

The class `.uni-section`, `.uni-section-primary`, `.uni-section-secondary`, `.uni-section-tertiary` can be used to create full-width visual sections that break away from this padding, using a negative margin. 

The background color values:

- `uni-section-primary` - grayish `rgb(231, 236, 240)`
- `uni-section-secondary` - white `rgb(255, 255, 255)`
- `uni-section-tertiary` - dark blue as in the menu sidebar `rgb(27, 41, 54)`

The class `.uni-card` can be used to create full-width visual sections that do not break away from the margin but have white background and drop shadow. 

----

The design linked above should be implemented in with HTML:

```html
<section class="uni-section-secondary">
  <slot name="page-header"><!--ALL ROUTES--></slot>
</section>
<section class="uni-section-primary">
  <section class="uni-card">
    <slot name="routes-table-title"><!--ROUTES--></slot>
    <slot name="routes-table"><!--table--></slot>
    <slot name="routes-new-route"><!--button--></slot>
   </section>
</section>
<slot name="save-button"><!--button, I skip the fact that it should be wrapped to have "success apperance --></slot>
<slot name="close-button"><!--button--></slot>
<slot name="delete-button"><!--button, I skip the fact that it should be wrapped to have "danger" apperance --></slot>
```

**Comment by PatrykSzwer** [comment]
Looks great for me, It would be awesome to have classes in uniform to manage those rectangled sections from starcounter-include's.

**Comment by tomalec** [comment]
Have you consider what would happen if you will concatenate two of such layouts?
```html
<section class="uni-section-secondary">
  <slot name="appa/page-header"><!--ALL ROUTES--></slot>
</section>
...
<slot name="appa/delete-button"><!--button, I skip the fact that it should be wrapped to have "danger" apperance --></slot>
<section class="uni-section-secondary">
  <slot name="appb/page-header"><!--ALL ROUTES--></slot>
</section>
...
<slot name="appb/delete-button"><!--button, I skip the fact that it should be wrapped to have "danger" apperance --></slot>
```
Then AppA's second section will overlap the AppB's button

**Comment by warpech** [comment]
Actually we must have a negative **top** margin only on `.uni-section::first-child`. Is this the solution?

**Comment by tomalec** [comment]
@warpech What's the reasoning behind `.uni-section-primary, .uni-section-secondary, .uni-section-tertiary` To me "All routes" is h1, routes is h2

**Comment by warpech** [comment]
Done in #32, being improved in #33.

**Comment by tomalec** [comment]
We have to revalidate padding approach due to lack of `:host`  polyfill  https://github.com/Starcounter/uniform.css/issues/39

**Comment by tomalec** [comment]
Improved by #33, closing as done
