### ISSUE TITLE
Consider [type=date] as a text field just like `[type=text]` and others

### ISSUE THREAD

**Issue by alshakero** [Starcounter/uniform.css#155]
I there there was a minor misunderstanding in https://github.com/Starcounter/underwear.css/issues/77. @miyconst wasn't talking about datepickers. He has a native `input` field that he needs to look like a normal underwear fields. 

I think he is right, we should add `[type=date]` to [this](https://github.com/Starcounter/underwear.css/blob/master/src/underwear.css#L238) list.

**Comment by miyconst** [comment]
@alshakero that's exactly what I was asking for.

**Comment by warpech** [comment]
Again, I don't see a good reason for this. The way to have a date picker in Uniform is to use `<input type="date">` for semantic reasons and then wrap it in `<uni-date-picker>` for presentation reasons, which hides `<input type="date">`. Why should we style `<input type="date">` if we are hiding it anyway?

**Comment by alshakero** [comment]
Because
- `<input type="date">` is part of `underwear.css`,
- `<uni-date-picker>` is part of `uniform.css`. 

I understand they're merged, but you only get the merged version if you import `uniform.css`. When you don't, you only have `underwear.css` styles.

**Comment by warpech** [comment]
Yes, but the reason for merging is to stop treating Underwear and Uniform as unrelated things. There are two layers of the same solution, and the date picker component part lives in the Uniform layer.

Related: https://github.com/Starcounter/StarcounterClientFiles/issues/102

**Comment by warpech** [comment]
This is sneaked in as https://github.com/Starcounter/uniform.css/commit/8e93efb7163c3750118ca6f2b18d8b2482f6292a, which is part of https://github.com/Starcounter/uniform.css/pull/157

**Comment by alshakero** [comment]
> This is sneaked in as 8e93efb, which is part of #157

FWIW. I never meant to push it in this PR. But there was a broken field in the demo which gave me even more incentive. 

![image](https://user-images.githubusercontent.com/17054134/43293638-92c5c71a-913b-11e8-83bf-b8299ef8c329.png)

From: https://starcounter.github.io/uniform.css/

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/uniform.css/pull/157.
