### ISSUE TITLE
In Firefox, <uni-data-table> does not render columns that do not have a explicit template

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#160]
### Steps to reproduce

1. Check out and run UniformDocs
2. Go to http://localhost:8080/UniformDocs/DataTable

### Expected

You should see 4 columns

### Actual

In Firefox, you see only 2 columns.

Compare:

<img width="750" alt="screen shot 2018-07-20 at 15 02 21" src="https://user-images.githubusercontent.com/566463/43003788-f1320ef2-8c2d-11e8-88c4-741b97074f8a.png">

![screen shot 2018-07-20 at 15 02 13](https://user-images.githubusercontent.com/566463/43003790-f158db90-8c2d-11e8-8f8a-c0b1accd5546.png)

**Comment by tomalec** [comment]
Isolated as purely `uni-date-table` vs `dom-bind` issue https://github.com/Starcounter/uniform.css/issues/166

**Comment by warpech** [comment]
Closing this issue as tracked in #166
