### ISSUE TITLE
[uni-data-table] Generated columns does not work in `dom-bind`

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#166]
### Steps to reproduce
1. Create `<dom-bind>` with `<uni-data-table>`
2. Provide configuration object with `Columns` for a table which is not mentioned in HTML markup.

```html
<dom-bind>
  <template>
    <uni-data-table
      provider='{
   "Columns": [{
        "DisplayName": "Header",
        "PropertyName": "FirstName"
    }],
    "Pagination": {
        "CurrentPageIndex$": 0,
        "PageSize$": 1,
        "PagesCount": 1
    },
    "SelectedRows": [],
    "Pages": [{
        "Rows": [{
            "FirstName": "It works!"
        }]
    }],
    "TotalRows": 1
}'>
    </uni-data-table>
  </template>
</dom-bind>
```

#### Live Demo
https://glitch.com/edit/#!/sky-air?path=index.html:13:4

### Expected result
Column should be generated.

### Actual result
It is not generated in Firefox and Edge

### Browsers affected

- [ ] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari

### Versions
- Uniform: 0.4.1
- webcomponentsjs: 1.2.2
- Starcounter: n/a

**Comment by tomalec** [comment]
Investigation notes:
 - seems Shadow DOM Polyfill related, as works fine in FF with SD enabled.

**Comment by tomalec** [comment]
Today @PatrykSzwer discovered that this fix was incorrect, so we need to find a better one.

**Comment by PatrykSzwer** [comment]
Unfortunately fix for that broke generating columns, when user define some of them manually.

I described my uni-data-table with one custom column:
```
<uni-data-table provider="{{model.CategoriesDataTable}}" slot="assortment-manager/category-table" auto-pagination>
                <uni-data-table-column index="0">
                    <template>
                        <input type="text" value="{{item.Name$::change}}" />
                    </template>
                </uni-data-table-column>
            </uni-data-table>
```
and before fix everything was fine, but now Name column is rendered 2 times:
![image](https://user-images.githubusercontent.com/25042256/43893056-03f650b6-9bce-11e8-936f-de38b642a742.png)

`uni-data-table` element `__generatedColumns` looks like this:
![image](https://user-images.githubusercontent.com/25042256/43893107-279c8aa8-9bce-11e8-8705-33c241cf1b10.png)

**Comment by tomalec** [comment]
I isolated the problem to Vaadin and Polymer only https://github.com/vaadin/vaadin-grid/issues/1365

**Comment by warpech** [comment]
@tomalec this can be closed, right? Or is "Quickfix" not the desired fix?

**Comment by tomalec** [comment]
Was hoping to find a solution for polyfill-Polymer issue, but failed to do so. Let's not waste more time on that.
