### ISSUE TITLE
Regressions in recent changes

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#168]
I just noticed that there are some regressions between the current Uniform.css and what is in the last released version.

Compare the below screenshots. The current version with regressions is on the left:

![regressions](https://user-images.githubusercontent.com/566463/43587131-c2074390-9669-11e8-99c7-cf35ef09f95f.png)

@alshakero can you pls investigate? We need to fix this before the next release.

## App versions checked 

Uniform.css c8070c7abec0bda6ffb4b400b36fee5033fe0b3c
UniformDocs 14f43f35c63e335e62acab08e8a57c67e04ae39f

**Comment by alshakero** [comment]
Can you please try top commit from `master`? I can't reporduce this.

**Comment by warpech** [comment]
Yes, I pushed the reproduction with an explanation in the commit message: https://github.com/Starcounter/uniform.css/commit/4f4648ac88a5227e9b1c8d43bdf4b4a64f1c4259

I didn't try re-reproducing the problem with the gap under the last section, though.

**Comment by tomalec** [comment]
Sorry, but it seems I created duplicate issue, with a reason of this problem https://github.com/Starcounter/uniform.css/issues/169

**Comment by warpech** [comment]
Closing as tracked in #169

**Comment by alshakero** [comment]
I'll reopen this since https://github.com/Starcounter/uniform.css/issues/169 was closed.
