### ISSUE TITLE
Build process corrupts shadow styles

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#169]
### Steps to reproduce
1. Open source file, e.g. `/src/uniform/uniform.css`,
2. Find any `::slotted`,
3. Try to find it in dist file, e.g. `/dist/uniform.css`

#### Live Demo
n/a

### Expected result
The selectors should be there.

### Actual result
`::slotted(foo)` is replaced with `foo`.

### Browsers affected

n/a
### Versions
- Uniform: https://github.com/Starcounter/uniform.css/commit/a3bb45a19e9323f9392ee0213ac3d3920594a9fc

**Comment by warpech** [comment]
Issue #168 is a duplicate of this problem and contains steps to reproduce with a link to a branch that reproduces the problem.

**Comment by tomalec** [comment]
Compare lines https://github.com/Starcounter/uniform.css/blob/master/src/uniform/uniform.css#L269-L298 and https://github.com/Starcounter/uniform.css/blob/master/dist/uniform.unminified.css#L1596-L1613

**Comment by alshakero** [comment]
Yes the build now creates all the duplicate lightDOM rules for you. But it doesn't remove the shadow ones. 

Here are the rules you want, they're there https://github.com/Starcounter/uniform.css/blob/master/dist/uniform.unminified.css#L1453

It's explained here https://github.com/Starcounter/uniform.css/pull/157

**Comment by tomalec** [comment]
Closing as invalid
