### ISSUE TITLE
Add Uniform.css in the shadow root of uni-data-table

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#173]
Right now, the cell contents of `uni-data-table` are not styled according to Uniform/Underwear, because they are in its shadow room.

Add Uniform.css in the shadow root of `uni-data-table` to render them properly.

This was agreed today on Slack by @tomalec, @alshakero and me.

**Comment by alshakero** [comment]
PR here https://github.com/Starcounter/uniform.css/pull/174
