### ISSUE TITLE
Wrong path to the stylesheet in uni-data-table

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#175]
The URI at line https://github.com/Starcounter/uniform.css/blob/9fe077568ad57685323186eb7d8386e9e8d2e89a/components/uni-data-table/uni-data-table.html#L12 is wrong, because it assumes that this stylesheet is made available in a folder called `uniform.css`. This assumption is not neccessary, because from the library perspective it should not matter what is the path to it.

I suggest to change this URI to: `../../uniform.css`

**Comment by warpech** [comment]
Actually, it is wrong for another reason.

This URI is not resolved relative to the HTML Import, but to the main HTML document. The only way to make it work is to use `/sys/uniform.css/uniform.css` or set the URL dynamically using a script. I vote for `/sys/uniform.css/uniform.css` for now.

This problem can be clearly reproduced on the UniformDocs "Data Table" page.

This is urgent, because all inputs and buttons in data tables look bad now.

**Comment by tomalec** [comment]
I believe we should not hardcode the path, as it's hard to maintain. There is the Polymer way to resolve paths in Polymer templates. (Polymer imports are handled by HTML Import path resolutions, the ones in `<template>` are left intact, so consumer of `template` => Polymer need to handle that)

https://www.polymer-project.org/2.0/docs/devguide/dom-template#urls-in-templates
