### ISSUE TITLE
Consider allowing styling links as buttons and vice-versa

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#186]
Today @PatrykSzwer shown a use-case, where he would like to style distributed `<a>` as a `uni-primary-button`.

It would be nice to be able to do just
```html
<div class="uni-primary-button"><slot name="anchor"></slot></div>
```

However it was not working as our selector matches only `button`:
https://github.com/Starcounter/uniform.css/blob/master/src/uniform/uniform.css#L22

We could easily change it to match both:
```css
.uni-primary-button > ::slotted(button),
.uni-primary-button > ::slotted(a)
```

The question is do we want to support/promote such usage

So far we fall back to:
```html
<style>
 /** set of styles to make distributed a, to look like a button content */
</style>
<div class="uni-primary-button"><button><slot name="anchor"></slot></button></div>
```

//cc @warpech @alshakero

**Comment by alshakero** [comment]
It's worth nothing that wrapping the anchor with button will not work since the anchor will have blue text.

**Comment by tomalec** [comment]
`*` is tricky, as it matches `<template>`, `<imported-template>`, and other undesired elements. I'd stick with YAGNI and `button, a`

**Comment by warpech** [comment]
What is the use case for this?

**Comment by alshakero** [comment]
here is a real one https://github.com/Starcounter/Images/pull/151#issuecomment-417932359

**Comment by warpech** [comment]
PR https://github.com/Starcounter/uniform.css/pull/190
