### ISSUE TITLE
Consistent prefix in class names

### ISSUE THREAD

**Issue by warpech** [Starcounter/Uniform.css#2]
In https://github.com/Starcounter/Uniform.css/blob/5ace19b7911d4fd4d5f452f0fef35d528244be6c/src/uniform.css, only some classes have a `uniform-` prefix, while others do not have that. 

This should be consistent.

I know that the most popular CSS framework (Bootstrap) does not have prefixes, but I think we should, for the following reasons:

1. In case of Underwear.css, **implicitness** is the king. In case of Uniform.css, **explicitness** is the king. I would like this boundary to be clearly visible.
2. App solutions are made of dozens unrelated apps. It is comforting to see what is the origin of some class. Therefore, I would expect Uniform.css classes to be prefixed with `uniform-` and app classes prefixed with `<appname>-`.
3. By giving a good example of using prefixes, we encourage app developers to do the same.

@Starcounter/sc-apps, @Starcounter/webplatformteam maybe someone has a different opinion?

**Comment by miyconst** [comment]
I agree with @warpech, only one question/suggestion. Th `uniform-` prefix is a bit long, maybe we could use `uf-` instead?

**Comment by warpech** [comment]
I agree. How about the prefix: `uni-` for classes and CSS variables. That would be more readable than "uf-`.

**Comment by miyconst** [comment]
I like the `uni-` prefix.

**Comment by PatrykSzwer** [comment]
I'll add those prefixes to our classes in uniform by the way with this PR https://github.com/Starcounter/Uniform.css/pull/5

**Comment by PatrykSzwer** [comment]
Right now all classes in uniform has `uni-` prefix. I think this can be closed.
