### ISSUE TITLE
Alerts are not styled correctly according to design

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/uniform.css#21]
Current alert look:
![image](https://user-images.githubusercontent.com/25042256/35980186-5fd883c2-0cea-11e8-92a6-103dd2eb631a.png)

Alert according to design:
![image](https://user-images.githubusercontent.com/25042256/35980204-6c57b3b6-0cea-11e8-8655-962525c875f5.png)

**Comment by tomalec** [comment]
@PatrykSzwer  Could you add the source code/snippet for the actual result? `uni-alert-*`s are wrappers, so make sure you attach a class to wrapping element.

**Comment by tomalec** [comment]
@warpech should we make `X` icon/button element and functionality in uniform, or should we leave up to the user to add or not the closing button, then implement the behavior on their own?

**Comment by tomalec** [comment]
BTW, I think we should rename `.uni-alert-*` to `.uni-alert-*-wrapper` with a same not as for buttons.

**Comment by warpech** [comment]
> BTW, I think we should rename .uni-alert-* to .uni-alert-*-wrapper with a same not as for buttons.

I was discussing it with Patryk and our conclusion is that wrapper is only a notation that we use for things that we wish were possible as `<slot class="uni-...">`. My impression is that it does not apply to things such as `uni-section`, `uni-card`, `uni-alert`. Do you think it applies to all elements?

**Comment by warpech** [comment]
> @warpech should we make X icon/button element and functionality in uniform, or should we leave up to the user to add or not the closing button, then implement the behavior on their own?

I think that the X should be an optional slot for now.

In future it would be part of Uniform, but that would mean that Uniform needs to have its own scripts or custom elements to hide the alert.

**Comment by warpech** [comment]
@tomalec pls make sure the alerts on the demo page look as in Anders designs

**Comment by tomalec** [comment]
Covered in https://github.com/Starcounter/uniform.css/pull/33

**Comment by tomalec** [comment]
There is a conceptual problem regarding close button, I'd really appreciate a meeting on this, as the desired behavior of the alert class is not specified.

1. If it's meant to create an alert box, then close button is not a problem,
2. If it's meant to create an alert box for each of slotted elements (for example to dynamically create this box when content arrives, then there is nowhere to attach the close button. You don know to which box, what if there is close button in outer content but no alert message etc.

**Comment by warpech** [comment]
I will make a new issue out of this to discuss only the close button and the presence of the div in the Shadow DOM.

**Comment by warpech** [comment]
The discussion about closing of the alert can be continued in https://github.com/Starcounter/uniform.css/issues/50
