### ISSUE TITLE
Radio buttons needs some love

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#28]
As noticed by @alshakero in https://github.com/Starcounter/uniform.css/pull/26#discussion_r167866319 radio buttons by default have no margins, and are barely clickable, see https://starcounter.github.io/uniform.css/

@andwah could we consider adding some sugar to it?

**Comment by andwah** [comment]
> could we consider adding some sugar to it?

certainly!,  ill give it a try first thing tomorrow.

**Comment by andwah** [comment]
![image](https://user-images.githubusercontent.com/2656996/36194819-85435576-116b-11e8-936b-8816b65fc47c.png)

**Comment by warpech** [comment]
This is the same problem as custom compositions. The above design is achievable but has side effects.

**Comment by PatrykSzwer** [comment]
@andwah says that for now we can just use default browser radiobuttons but eventually when we will have time we should, as @tomalec said, give some love to them, especially if It's possible to achieve such styling with uniform.

**Comment by warpech** [comment]
For the time being, can you just do the same treatment for radio buttons in Underwear.css that is done for checkboxes?

```css
input[type='checkbox'] {
  margin-right: 5px;
  vertical-align: middle;
  background: #fff;
}
```

**Comment by warpech** [comment]
The look and feel of radios and checkboxes in Underwear.css is unified in this PR: https://github.com/Starcounter/underwear.css/pull/65

More complex UI overhaul should be done as part of future Uniform.css work on checkboxes and radios, which is already tracked in https://github.com/Starcounter/uniform.css/issues/24

Closing as tracked in other issues
