### ISSUE TITLE
Label container

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#29]
Current implementation of `.uni-label-control` does not match the design

**Comment by alshakero** [comment]
The margin is 7px more than it should be
![image](https://user-images.githubusercontent.com/17054134/36335011-4a38b7b4-137d-11e8-8523-71f7d5d82046.png)

**Comment by tomalec** [comment]
Closing as implemented in https://github.com/Starcounter/uniform.css/pull/42
