### ISSUE TITLE
Add demo/preview page of Uniform classes and posibilities

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/uniform.css#3]
If We want people to use our amazing framework, we have to show them, what can It does and how to use it. I suggest adding some demo page, that contains every our class from uniform, code snippet how to use it and example how it should look. We can make it at some custom page for it, or we actually could make a page in Kitchensink with all examples.

Here's how vaadin example pages look like: https://vaadin.com/elements/vaadin-date-picker/html-examples/date-picker-basic-demos

cc: @alshakero, @warpech

**Comment by mmnosek** [comment]
I think that it would be super useful if available together with Kitchensink.

**Comment by PatrykSzwer** [comment]
@alshakero created some first proposition of demo page here: https://starcounter.github.io/Uniform.css/ We should add this to a repository title like It's done in underwear.css, or to a readme after current PR with readme scratch is merged.

**Comment by tomalec** [comment]
https://github.com/Starcounter/StarcounterClientFiles/issues/31#issuecomment-363793906
> There should be 2 demo pages:
>
> - one without Underwear (for principle)
> - anouther one with Underwear (for our convenience)

**Comment by tomalec** [comment]
Implemented in @26 ready at https://starcounter.github.io/uniform.css/
