### ISSUE TITLE
Button wrappers should be inline-blocks

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#31]

**Comment by warpech** [comment]
The reason for this is that otherwise, divs with class `uni-sucess-button` cause the button to reserve the whole line.

**Comment by warpech** [comment]
Implemented in PR #33 to save the effort of reviewing many PRs in a short time.

**Comment by tomalec** [comment]
Fixed in https://github.com/Starcounter/uniform.css/pull/33
