### ISSUE TITLE
Should sections be grids?

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#37]
Moved from https://github.com/Starcounter/uniform.css/pull/33#issuecomment-366230554:

----

@PatrykSzwer:

> I had to use more than couple of times, and most common was the solution with grid to provide correct width to section. Maybe we should somehow add this to uniform? As another version of section class, like uni-primary-section-grid or something like that (maybe something shorter)

----

My comment on this is that looking at @andwah designs, I see that all sections are grids. Sometimes they are just grids with one column. So, for me, it might be fine to just add these rules to `uni-*-section`:

```css
display: grid;
grid-gap: var(--uni-host-padding-horizontal);
```

I think that it depends mostly on @andwah. @tomalec, @alshakero WDYT?

Alternatively, we could use `uni-primary-section uni-grid`, but that's verbose.

**Comment by tomalec** [comment]
Making section a grid makes sense to me. Hopefully making a heading-only, block section a `grid` would not be an overkill for the browser.

**Comment by warpech** [comment]
We made a decision that:

- sections will not be grid by defaults
- span cards will be inline by default
- div cards will be block by default
- cards are also useful as inline-block

All the above cases should be shown on the demo page

@tomalec will do that

**Comment by tomalec** [comment]
Fixed by https://github.com/Starcounter/uniform.css/pull/47
