### ISSUE TITLE
Add more classes to uniform.css

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Uniform.css#4]
I would actually take a moment to think about some other classes that could be potentially useful and add them to uniform. I think good idea would be to ask on teams what would they expect from uniform and implement their ideas?
For me we could:
- Add some class to connect label and input like It's done in vaadin-datepicker (smaller label above input):
![image](https://user-images.githubusercontent.com/25042256/35431422-b3210004-027c-11e8-9536-b768b3e28a05.png)

I think there was some class for this in old uniform but only for paper-input (but It could also be only spacing, I'm not sure)

- More classes for buttons, like danger etc. similar to those from bootstrap.
- Class for legend (This one I would really appreciate 🙏  since most of the headers in blendingEditor app are based on legend tag from bootstrap)

I'll update with some more, when something cames to my mind. What do You think guys?
cc: @alshakero @warpech

**Comment by warpech** [comment]
For convenience, can you place what pages in KitchenSink would use this?

**Comment by PatrykSzwer** [comment]
Closing as done.
