### ISSUE TITLE
Typography: Compare the header usage

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#43]
Currently, there is not enough coverage between the headers available in Underwear.css and the headers used in usage in Uniform.css/BlendingEditor.

1. In Underwear.css `<h1>`, `<h2>`, `<h3>` are so big that they are not used anywhere.
2. In BlendingEditor designs, the section title and the card title use the same font size. Should they both be implemented with `<h4>`, as they are now?

To be answered this week by the collaboration of @andwah and @PatrykSzwer.

**Comment by PatrykSzwer** [comment]
We agreed with @andwah to make headers more usable and related to headers from blending design. He will take care of this.

**Comment by andwah** [comment]
I have no experience on the releation between header's `h1 `to `h6` regarding sizes, weight etc.. but i made a first draft that we can begin to work on.


![image](https://user-images.githubusercontent.com/2656996/36492016-6bfe04d2-172c-11e8-9f5e-e1033532b932.png)

**Comment by warpech** [comment]
If I understand correctly, an app layout such as below, would only use `<h5>` and `<h6>`? 

Would `<h1>` - `<h4>` be used then at all? If not, let's make them used for TITLE and Subheader. 

![surface groups](https://user-images.githubusercontent.com/566463/36494364-24b29d94-1732-11e8-8a29-6c2e75797f45.png)

**Comment by warpech** [comment]
Disregard my previous comment.

I think it is fine to implement headers as proposed. In Uniform, we should style Title and Sub header using new classes: uni-title, uni-subtitle. WDYT?

**Comment by PatrykSzwer** [comment]
I'm not sure TBH. In one way, we shouldn't go too far from standard specification of HTML to save expected behavior, but in other I'm not sure about the usability of those `uni-title` and `uni-subtitle`, we will be just creating another <hx> tags IMO. 
I don't know, maybe lets ask @tomalec and @alshakero for opinions.

**Comment by warpech** [comment]
We didn't want app developers to dictate which `<button>` is the primary, in order to leave that decision up to the solution designer. We should do the same regarding the headers.

**Comment by andwah** [comment]
Some reading about heading (and more)
http://www.bbc.co.uk/guidelines/futuremedia/technical/semantic_markup.shtml#headings

**Comment by warpech** [comment]
I am working on this. I will create the class `uni-title` that resets the style to Roboto, 20px. This allows to use any `<hx>` tag in the app.

**Comment by warpech** [comment]
Implementation of `.uni-title` is in PR #60

The implementation of `<h1>` - `<h6>` according to @andwah's designs should be moved to Underwear.css

**Comment by warpech** [comment]
PR #60 is released.

The remaining task is tracked at https://github.com/Starcounter/underwear.css/issues/70
