### ISSUE TITLE
Create a two column layout with blue sidebar

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#44]
Two-column page layout should be moved to Uniform.css with colors as variables. All styles from `MasterPage.html` Shadow DOM should go to Uniform.

Leftover from https://github.com/Starcounter/Blending/pull/63#issuecomment-366098556

**Comment by andwah** [comment]
We were discussing this with @PatrykSzwer and we agreed that we should have helper classes in uniform that allows to create multiple columns layout, and on top of that we should create our two columns blending editor layout. That would make it more customizable and allows user to implement different approaches with uniform. 
This solution depends if we want uniform to be more like a elements styles helper or theme helper?

**Comment by warpech** [comment]
> We were discussing this with @PatrykSzwer and we agreed that we should have helper classes in uniform that allows to create multiple columns layout, and on top of that we should create our two columns blending editor layout. That would make it more customizable and allows user to implement different approaches with uniform.

Could you make designs of such?

> This solution depends if we want uniform to be more like a elements styles helper or theme helper?

Both.

Uniform.css is a set of helper CSS classes to:

- apply contextual look and feel for native HTML elements (such as `.uni-primary-button`, `.uni-alert-success`, etc)
- implement typical UI patterns (such as `uni-section-primary`, `uni-card`, `uni-label-control`, etc)

What you describe fits the second use case well.

**Comment by warpech** [comment]
To avoid conflicts, this should be done after https://github.com/Starcounter/Blending/issues/85

**Comment by warpech** [comment]
Provisional implementation in https://github.com/Starcounter/Blending/pull/105

**Comment by warpech** [comment]
Closing as done in https://github.com/Starcounter/uniform.css/pull/61
