### ISSUE TITLE
What is the relation between designs and uniform & underwear?

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#45]
The questions raised in https://github.com/Starcounter/uniform.css/pull/42#issuecomment-366445107

We need to decide whether the design, numbers, etc. given by @andwah in the pictures apply for which setup.

1. Underwear in light, uniform in shadow & all elements in the light,
2. Underwear in light, uniform in shadow & elements wherever,
3. Underwear in light, uniform in shadow, underwear in shadow & elements wherever,

Then what about the design, demos, samples for other cases?

---

Supporting the case 2. "Underwear in light, uniform in shadow & elements wherever" would require us to include entire underwear in uniform, so I'd say it's no-go.

Personally, I'd choose 1 & 2. But I'm still not sure about demoing, case 2.

//cc @alshakero @PatrykSzwer @warpech

**Comment by warpech** [comment]
In my mind this was already discussed regarding buttons that we do:

1. Underwear in light, uniform in shadow & all elements in the light,
   - if the developer or designer wants elements in shadow, it is possible, but they have to include Underwear in shadow explicitly

@tomalec is that OK?

**Comment by PatrykSzwer** [comment]
We talked a little with @andwah and We agree that
> Underwear in light, uniform in shadow & all elements in the light

is the way that we vote for.

**Comment by warpech** [comment]
@tomalec does Uniform.css or the demo page need any adjustments then?

**Comment by tomalec** [comment]
We have examples of 
> 3. Underwear in light, uniform in shadow, underwear in shadow & elements wherever,

> 1. Underwear in light, uniform in shadow & all elements in the light,
>     -    if the developer or designer wants elements in shadow, it is possible, but they have to include Underwear in shadow explicitly
>
>@tomalec is that what you mean by 3?

yes

-----

> If point 3 makes no difference for the Uniform demo other than `@import underwear.css`

It also requires adding respective elements to the shadow root

**Comment by warpech** [comment]
We all agreed on:

> Underwear in light, uniform in shadow & all elements in the light,
> - if the developer or designer wants elements in shadow, it is possible, but they have to include Underwear in shadow explicitly

I added a clearer explanation of that in 2e6352d643e72cc99993026a35b9aad4ff1b4f0d (PR #59)

**Comment by warpech** [comment]
Closing as done
