### ISSUE TITLE
Colors might be a little off

### ISSUE THREAD

**Issue by alshakero** [Starcounter/uniform.css#6]
All details here: https://github.com/Starcounter/Underwear.css/issues/1

**Comment by warpech** [comment]
Marcin will discuss it with @andwah to keep it as a filter.

**Comment by andwah** [comment]
Correct and current button color values

```
       WANTED      REAL
--------------------------------------
White: #FFFFFF    #FFFFFF   OK
Blue:  #0084B4    #0081B2   MISSMATCH
Red:   #DF4534    #E04A38   MISSMATCH
Green: #3FA13F    #43A043   MISSMATCH
```
![image](https://user-images.githubusercontent.com/2656996/36471699-b9ce61da-16ef-11e8-8a12-4b357ed86e38.png)

**Comment by PatrykSzwer** [comment]
We discovered that this differences in colors are result of the bug in @andwah snippeting program. Colors are actually correct so I'll close this issue.
