### ISSUE TITLE
Uniform doesn't work if imported by link tag in ShadowDOM in MS Edge

### ISSUE THREAD

**Issue by alshakero** [Starcounter/uniform.css#63]
Works: 
```html
<style>
    @import '/sys/uniform.css/uniform.css';
</style>
```

Does not:
```html
<link rel="stylesheet" href="/sys/uniform.css/uniform.css">
```

I spent two hours trying to find the real reason but Edge DevTools is pretty much useless, I couldn't deduct anything from it, trail and error came to the rescue though, I edited HTML and refreshed and saw the results, I mention this because I really wanted to understand why this happens, but DevTools needs 5 mins to render after every page refresh, and terribly slow then. 

All I could discover is that the polyfill adds this attribute to the link tag, `type="import-disable"` as in
```html
<link class="style-scope starcounter-include" href="/sys/uniform.css/uniform.css" rel="stylesheet" type="import-disable">
```

Which gives me the sense that this is by design. There is a type attribute in the spec if `<link>` But no mention of `import-disable` value. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) on `<link>`.

It's worth nothing that adding this attribute to a `<link>` tag renders it useless, even in Chrome. 

/cc @tomalec @warpech

**Comment by alshakero** [comment]
And I'll go ahead and mention that it definetly feels something to click on a link in the spec itself and find @tomalec's issue 😄 

![image](https://user-images.githubusercontent.com/17054134/37032943-7ac44752-2144-11e8-8ba3-c69d4dd6df08.png)

https://github.com/w3c/webcomponents/issues/628

**Comment by tomalec** [comment]
Above issue is about the fact link relbstylesheet is supported, but other ar not. Therefore above code should work. 

I'd susspect this is a bug in polyfill.

**Comment by tomalec** [comment]
Maybe it has to do something with https://github.com/webcomponents/shadycss/issues/108

**Comment by tomalec** [comment]
https://github.com/webcomponents/html-imports/blob/master/README.md#imported-stylesheets-in-ieedge

**Comment by tomalec** [comment]
It seems to ne abug in html imports polyfill could you isolate it to a jsbin and file an issue for https://github.com/webcomponents/html-imports/blob/1d44a51cf39d8229331f85e815df78cfbb8383b4/src/html-imports.js

So, the google search for common problems with WC will show more of your issues ;)

**Comment by alshakero** [comment]
Turns out even using:

```html
<style>
    @import '/sys/uniform.css/uniform.css';
</style>
```
Doesn't always work. 

This is what I'm getting
![image](https://user-images.githubusercontent.com/17054134/37090954-ad64cab6-2206-11e8-95a8-87701fa79d10.png)

The left bar is working, but the `blendingeditor.css` file isn't being applied. I'm investigating.

**Comment by tomalec** [comment]
I think I found a reason in HTML Import's polyfill https://github.com/webcomponents/webcomponentsjs/issues/1008

I'll try to find a workaround, as this is a blocking issue for solving FOUC of shadow DOM styles.

**Comment by tomalec** [comment]
Closing as done in https://github.com/Juicy/imported-template/pull/59
