### ISSUE TITLE
Why do we need those classes?

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Uniform.css#7]
I found we have non-prefixed classes like:
```
.primary...
.success...
.danger...
.button-outline...
```
Do we even need those rules? If we do I think they should be prefixed.

//cc @alshakero

**Comment by warpech** [comment]
They are being prefixed in https://github.com/Starcounter/Uniform.css/pull/5.

We need them to have Bootstrap-like capabilities for styling of the buttons.

Closing in favor of https://github.com/Starcounter/Uniform.css/issues/2

Thanks for reporting
