### ISSUE TITLE
[date-picker] input-label binding

### ISSUE THREAD

**Issue by tomalec** [Starcounter/uniform.css#74]
At https://github.com/Starcounter/uniform.css/pull/70#discussion_r181597838 we started the discussion whether `uni-date-picker` should also wrap `<label>` element, to render it as part of consistent label - input control pair. This is the actual example of how we can solve [Somewhat intelligent form's label layout - RebelsLounge#14](https://github.com/Starcounter/RebelsLounge/issues/14).

**Comment by tomalec** [comment]
_@warpech [wrote](https://github.com/Starcounter/uniform.css/pull/70#discussion_r181597838):_

This is my only essential disagreement in this PR: I think that `uni-date-picker` should **only** wrap `input` for providing a nicer date picker. Labels should be out of scope of wrapping. We will be using Uniform.css labels, not Vaadins labels. 

You will not be able to build a consistent looking UI if some fields use Uniform labels and the datapicker uses a Vaading built-in label.

Please remove the support for wrapping labels from `uni-date-picker`.

**Comment by tomalec** [comment]
_@tomalec[wrote](https://github.com/Starcounter/uniform.css/pull/70#discussion_r181682420):_

I thought of it as finally a way to be able to support consistent vaadin-like labels if we want. And approach Starcounter/RebelsLounge#14

**Comment by tomalec** [comment]
_@tomalec [wrote](https://github.com/Starcounter/uniform.css/pull/70#discussion_r181683063):_

Especially speaking of `uni-date-picker` as a POT for vaadin developers. As that was the main intention to create it. To test and provide a set technical ways to integrate those two, to porvide platform featureset for Vaadin devs to do whatever they imagine as Design System.

I agree we should not use it in our apps right now, but I think it's valuable to show that approach to Vaadin

**Comment by tomalec** [comment]
_@warpech [wrote](https://github.com/Starcounter/uniform.css/pull/70#discussion_r181697837):_

I think that showing it this way might actually cause them to miss the point. We want to emphasize that the label presentation should be a separate concern from the actual UI control (datepicker).

**Comment by warpech** [comment]
I like when there is only one way to do things.

So, I propose to assign label to the date picker in the following way:

```html
<uni-form-item>
  <slot slot="label" name="label-for-my-input"></slot>
  <uni-date-picker>
    <slot name="my-input"></slot>
  </uni-date-picker>
</uni-form-item>
```

`uni-form-item` (aka `uni-label-control`, let's have a vote about the name) is a proposed custom element that creates visual, usable and accessible pair between a label and any other element.

Vaadin's equivalent is [vaadin-form-item](https://vaadin.com/components/vaadin-form-layout/html-examples/form-layout-basic-demos):

```html
<vaadin-form-item>
  <label slot="label">Select a date</label>
  <vaadin-date-picker></vaadin-date-picker>
</vaadin-form-item>
```

**Comment by warpech** [comment]
Closing as we agreed that it will be as explained in https://github.com/Starcounter/uniform.css/issues/74#issuecomment-384617582.

The implementation of `uni-form-item` is tracked in https://github.com/Starcounter/RebelsLounge/issues/261

**Comment by tomalec** [comment]
@warpech Shouldn't we keep this issue to track removing of this functionality from `uni-date-picker`?

**Comment by warpech** [comment]
Tracked in https://github.com/Starcounter/uniform.css/issues/99
