### ISSUE TITLE
[date-picker] Control the width of the datepicker through CSS

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#78]
Currently, this has no visible difference between:

```html
<uni-date-picker style="width: 100px"><slot></slot></uni-date-picker>
<uni-date-picker style="width: 200px"><slot></slot></uni-date-picker>
<uni-date-picker style="width: 100%"><slot></slot></uni-date-picker>
```

The inner `vaadin-date-picker` should be full-width, so that it will adapt to the width of `uni-date-picker`.

**Comment by tomalec** [comment]
Please note, that I will only make it work for `width` as `height` is broken on Vaadin side https://github.com/vaadin/vaadin-date-picker/issues/546 
If setting height is also very important and urgent right now, please create a new issue so we could try to find a workaround/fork `vaadin-date-picker`

**Comment by tomalec** [comment]
`width` and `height` can now be set for `uni-date-picker`, PR https://github.com/Starcounter/uniform.css/pull/84 delivers full feature and is ready for the review.

**Comment by tomalec** [comment]
Released in https://github.com/Starcounter/StarcounterClientFiles/releases/tag/3.6.1, should be available in upcoming Starcounter develop build (`>2.4.0.6057`)
