### ISSUE TITLE
[date-picker] The default first day of the week should be Monday

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#79]
The first day of the week in the default locale should be Monday.

Now it is Sunday.

**Comment by tomalec** [comment]
Fixed and waiting formal GH approval, https://github.com/Starcounter/uniform.css/pull/83

**Comment by tomalec** [comment]
Released in https://github.com/Starcounter/StarcounterClientFiles/releases/tag/3.6.1, should be available in upcoming Starcounter develop build (`>2.4.0.6057`)
