### ISSUE TITLE
Not all rules work with slotted buttons

### ISSUE THREAD

**Issue by warpech** [Starcounter/Uniform.css#8]
Some of the rules are designed only for light DOM and will not work with buttons slotted from Shadow DOM. I mean the following lines:

- https://github.com/Starcounter/Uniform.css/blob/e844234ae2da5f32cb987f6606191dbe3d7a3f02/src/uniform.css#L31-L54 - I don't understand where it is used. Please remove because it is made redundant by `uni-button-danger`, `uni-button-primary`, `uni-button-success` (that was also reported in #7)
- https://github.com/Starcounter/Uniform.css/blob/e844234ae2da5f32cb987f6606191dbe3d7a3f02/src/uniform.css#L134-L165

**Comment by PatrykSzwer** [comment]
I've covered this issue in this PR: https://github.com/Starcounter/Uniform.css/pull/11

**Comment by tomalec** [comment]
Technically those rules could be as well used for elements distributed through Shadow DOM, so "will not work with buttons slotted from Shadow DOM" is not the case here.
 The question is, whether we want to have something like:
- `uni-button-outline`
- `uni-primary`
- `uni-success`
- `uni-danger`

**Comment by PatrykSzwer** [comment]
I would suggest to stick with our implementation of `wrappers` right now, and get rid of any other confusing selectors.

**Comment by warpech** [comment]
> The question is, whether we want to have something like:
>
> - uni-button-outline
> - uni-primary
> - uni-success
> - uni-danger

We use the designs made by @andwah as the primary reference:

- https://drive.google.com/drive/u/0/folders/12TeSCAPs0v5unQ-CnckDCqelpTCj5qP4
- https://drive.google.com/drive/u/0/folders/1YnNLer6FP6AgEGQM--ma_7i1mUkMwfHf

The reference designs do not have outlined buttons, so `uni-button-outline` should be removed from Uniform.

The reference designs do have primary/success/danger buttons that already expressed in Uniform by classes `.uni-primary-button-wrapper`/`.uni-success-button-wrapper`/`.uni-danger-button-wrapper`. So `uni-primary`, `uni-success`, `uni-danger` are redundant.

They do not have examples of alert callouts (like https://getbootstrap.com/docs/4.0/components/alerts/) and I think it should be added. Anders, can you pls do that on some new screen? It is part of Uniform, not Underwear.

**Comment by andwah** [comment]
I added "alert" to our design (the close button is optional)

![image](https://user-images.githubusercontent.com/2656996/35910158-003f1f7e-0bf6-11e8-8828-be003321cf99.png)

**Comment by warpech** [comment]
The original problem is fixed in https://github.com/Starcounter/Uniform.css/pull/11

I have moved the alerts to a separate issue: https://github.com/Starcounter/Uniform.css/issues/12

Thanks everyone!
