### ISSUE TITLE
[date-picker] Live demos are missing component dependencies

### ISSUE THREAD

**Issue by platosha** [Starcounter/uniform.css#87]
Got error: `Failed to load resource: the server responded with a status of 404 ()` for `/vaadin-date-picker/vaadin-date-picker.html` in the console. Live demos for `uni-date-picker` are unstyled and missing the actual date picker.

Takes place on:
- https://tomalec.github.io/uni-date-picker/
- https://tomalec.github.io/uni-date-picker/index-material.html
- https://tomalec.github.io/uni-date-picker/index-polymer-binding.html

**Comment by tomalec** [comment]
Thanks for reporting!

Sorry, the links were corrupted, there is a PR to fix that https://github.com/Starcounter/uniform.css/pull/90.
In the meantime, you can use

- https://starcounter.github.io/uniform.css/components/uni-date-picker/
- https://starcounter.github.io/uniform.css/components/uni-date-picker/index-material.html
- https://starcounter.github.io/uniform.css/components/uni-date-picker/index-polymer-binding.html

**Comment by tomalec** [comment]
Fixed by https://github.com/Starcounter/uniform.css/pull/90
