### ISSUE TITLE
Importing Uniform.css in a custom element definition

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#94]
@malx122 reported today on the "App developer experience ref group" meeting that he would like to use parts of Uniform.css, such as the color variables inside of a custom element definition.

When he tries that, he gets a warning in Chrome:

> [Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

@malx122 proposes that perhaps we should package Uniform.css similarly to how Polymer's shared-styles are done.

@tomalec WDYT? Is there a simpler way?

**Comment by warpech** [comment]
@tomalec will create an example of a custom element that uses Uniform CSS custom properties and classes.

**Comment by tomalec** [comment]
Here is the example

```html
<!-- this element is needed to use HTML Imports in Shadow DOM, it's loaded by Starcounter app shell -->
<link rel="import" href="../enlighted-link/enlighted-link.html">
<script>
customElements.define('my-element', class extends HTMLElement{
    constructor(){
        super();
        this.attachShadow({mode: 'open'}).innerHTML = `
            <!-- use Uniform.css -->
            <link rel="stylesheet" href="uniform.css"/>
            <!-- load Uniform component -->
            <enlighted-link rel="import" href="components/uni-date-picker/uni-date-picker.html"></enlighted-link>
            <style>
                :host{display: block;}
                /* use Uniform CSS Variables */
                span{color: var(--uni-default-primary);}
            </style>
            <!-- use Uniform classes -->
            <div class="uni-section-secondary"><div class="uni-alert-success"><div><slot></slot></div></div></div>
            <span>--uni-default-primary</span>
            <!-- use Uniform component -->
            <uni-date-picker><inupt type="date"></uni-date-picker>
        `;
    }
});
</script>

<my-element>Hello world</my-element>
```
@malx122 Please confirm, if that's what you need.

**Comment by tomalec** [comment]
Closing as answered, please re-open if it's not enough for your use case, or I missed something.

**Comment by warpech** [comment]
Can you pls add it to the docs? `README.md` would be sufficient.

**Comment by tomalec** [comment]
Sure, but I'm a little bit afraid to blur the picture, as it is simply the way you use styles and custom element dependencies in any custom element.

**Comment by warpech** [comment]
If @malx122, a developer with 2 years of experience in Polymer could not figure it out then I think it is not that obvious and needs to be in the docs.

**Comment by tomalec** [comment]
Closing as documented in https://github.com/Starcounter/uniform.css/pull/108
