### ISSUE TITLE
Make sure that uni-date-picker is responsive

### ISSUE THREAD

**Issue by warpech** [Starcounter/uniform.css#96]
Make sure that `uni-date-picker` is responsive, i.e. uses the mobile look and feel of `vaadin-date-picker` when used on a mobile device.

This will be nicely demonstrated in KitchenSink when the related issue is done: https://github.com/Starcounter/KitchenSink/issues/312

**Comment by tomalec** [comment]
It probably will require updating `vaadin-date-picker` to the version that is not themable see https://github.com/Starcounter/uniform.css/issues/95#issuecomment-394405473

**Comment by tomalec** [comment]
Closing as done in https://github.com/Starcounter/uniform.css/pull/116
